### ISSUE TITLE
Offline interactive WebGL backend for VisPy

### ISSUE THREAD

**Issue by rossant** [vispy/vispy.js#13]
This allows one to automatically export a VisPy visualization in Python to an interactive HTML/JS document.

There are several components:
- [x] GLIR JSON exporter in VisPy (done by @izaid)
- [x] GLIR JSON importer in vispy.js (done by @izaid)
- [ ] JS version of the PanZoom transform (see a very old version [here](https://github.com/rossant/galry/blob/master/experimental/ipynb/jsplugins/ipynbgalry/ipynbgalry.js#L356)).
- [ ] a way to link a JS VisPy canvas to the PanZoom (need to emit UNIFORM GLIR commands, see [this](https://github.com/vispy/vispy.js/blob/master/test.html)). The same would need to be done for phy flavor of panzoom (some refactoring is planned there)
- [ ] A `--vispy-export=myviz.html` option that exports a Python script to a standalone interactive HTML/JS document depending on `vispy.min.js` (panzoom support only for now, we can add other cameras later)
- [ ] An IPython notebook backend (`ipynb_standalone`, say) that integrates all JS code directly into the notebook (and require `vispy.min.js`), so that the visualization remains alive and interactive in notebook exports like nbviewer

@cgestes is that something you'd like to tackle after the GUI? It would be very, very useful to many people, and we could use it in phy as well. The primary use case would be to exchange live interactive notebooks with nbviewer (users would be able to pan and zoom in the data). In the [notebook example](http://nbviewer.ipython.org/github/kwikteam/experimental/blob/master/test_data/test_1.ipynb) I sent earlier, I had to do screenshots manually. With the offline backend I would have had nothing to do, and the plots would be interactive!

**Comment by larsoner** [comment]
So this would allow people to have `vispy` visualizations in the browser, rendered in `WebGL`, without Python running client or server side?

**Comment by rossant** [comment]
Yes. But you have to write the interactivity logic by hand in JavaScript for now. For pan and zoom, say, this is quite easy because you just have to update uniforms (the shaders do all of the work). More generally, this is easy as soon as interactivity is mostly implemented on the shaders.

**Comment by larsoner** [comment]
Cool. cc @jyeatman this might be useful down the line.

**Comment by djhoese** [comment]
The VisPy Python library now depends on a new `jupyter_rfb` backend (to be released in 0.8.0, not out yet). As such, we have deprecated and removed the `ipynb_webgl` backend. This means the `vispy.js` project will not be used by the VisPy project anymore and will not receive active development. I'm closing this issue because of this and will be archiving the repository making it read-only.
