### ISSUE TITLE
test_commands.html does not work in chromium

### ISSUE THREAD

**Issue by bollu** [vispy/vispy.js#15]
Like the title says, `test_commands.html` with the points example doesn't seem to work in chromium. It does work in firefox. The console log only has `event loop started`

Screenshot:
![screenshot from 2015-06-25 02-03-40](https://cloud.githubusercontent.com/assets/1694861/8340828/a19f04b2-1ade-11e5-877a-f7b11fd500d6.png)

**Comment by rossant** [comment]
what about chrome? have you checked https://wiki.archlinux.org/index.php/Chromium#WebGL ?

**Comment by bollu** [comment]
no better in chrome, unfortunately

`test_commands.html` does not run:
![screenshot from 2015-06-25 02-33-56](https://cloud.githubusercontent.com/assets/1694861/8341496/f5b05318-1ae2-11e5-9d92-39a0cfca9118.png)

`test.html` example runs:
![screenshot from 2015-06-25 02-33-59](https://cloud.githubusercontent.com/assets/1694861/8341465/b82fd2ac-1ae2-11e5-96a6-14cff80106cb.png)

And, I've tried running other webGL stuff in chrome (chrome experiments and such) to check if webGL works. They all work. `vispy.js/test.html` also works.

**Comment by rossant** [comment]
ok. I didn't write test_commands, I can't remember who did, can you check (git blame or something?)

**Comment by bollu** [comment]
sure

**Comment by bollu** [comment]
looks like @izaid did.

**Comment by bollu** [comment]
It looks like its rendering points, but scaled down? Like, the actual rendered points in firefox are large.

**Comment by izaid** [comment]
I wrote it. We never tested it in Chromium...

**Comment by djhoese** [comment]
The VisPy Python library now depends on a new `jupyter_rfb` backend (to be released in 0.8.0, not out yet). As such, we have deprecated and removed the `ipynb_webgl` backend. This means the `vispy.js` project will not be used by the VisPy project anymore and will not receive active development. I'm closing this issue because of this and will be archiving the repository making it read-only.
