### ISSUE TITLE
Can we also produce nonminified vispy.js in build dir?

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy.js#5]
Debugging is a pain otherwise. Maybe I don't get how source maps are supposed to work. Or my browser (ff) does not use them? Anyway, having a non-minified version would help a lot :)

**Comment by rossant** [comment]
why not, @ctaf42 do you know how to do that?

**Comment by cgestes** [comment]
debugging works well with the source maps.

have you tried to build vispy.js with gulp? and to link the .map at the right place?

ls -la vispy/vispy/html/static/js/
vispy.min.js
vispy.min.js.map -> <somewhere>/vispy.js/dist/vispy.min.js.map

**Comment by almarklein** [comment]
I did build with gulp and just did `<script src="/path/to/vispy.min.js"></script>`. How do I tell my browser to use the source map?

**Comment by cgestes** [comment]
the path to the sourcemap is included in vispy.min.js. you have to activate sourcemap in your debugger if it's not already done though. (I know there is an option, I never had to use it)

then you check in network if he can fetch the .map file

If you use gulp dev then the bundle is rebuild when you save your sources, and it's very straighforward to work.

**Comment by cgestes** [comment]
@almarklein created a chat with you on gitter.im. Will be easier to help you.

**Comment by cgestes** [comment]
fixed by #6.
please close
