### ISSUE TITLE
Question about c.$el.resize

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy.js#7]
I'm embedding vispy.js in bokeh.

In this code:

```
    c.$el.resize(function (e) {
        c.resize([e.width(),
        e.height()]);
      }
```

I get `TypeError: c.$el.resize is not a function`. I suppose this relies on some jQuery plugin which is perhaps not loaded. Looked into it, but I could use some help on what plugin I might be missing.

**Comment by rossant** [comment]
This comes from http://jqueryui.com/resizable/

But @cgestes is currently improving this

**Comment by cgestes** [comment]
dont call .resizable() and it wont depend on that jquery part.

**Comment by almarklein** [comment]
mmm... I don't think that I do. Will look further. Thanks!
